---
- name: Configurar red estática en eth0
  template:
    src: interfaces.j2
    dest: /etc/network/interfaces.d/eth0.cfg
  notify: Reiniciar red

- name: Instalar paquetes necesarios
  apt:
    name:
      - net-tools
      - iproute2
    state: present
    update_cache: yes

- name: Habilitar IP forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
    reload: yes
